require("conf.plugins.lazy")
require("conf.plugins.telescope")
require("conf.plugins.telescope-undo")
require("conf.plugins.treesitter")
require("conf.plugins.mason")
require("conf.plugins.lsp")
require("conf.plugins.lua-line")
